################################################################################
### utilities ##################################################################
################################################################################
brew 'dnsmasq'
brew 'imagemagick'
brew 'jq'
brew 'openssl'
brew 'ttyrec'
brew 'unrar'
brew 'wget'
brew 'xz'
cask 'avira-antivirus'
cask 'cleanmymac'
cask 'keybase'
cask 'wireshark'
mas  'CleanMyDrive 2', id: 523620159
mas 'Monosnap', id: 540348655
