################################################################################
### utilities ##################################################################
################################################################################
brew 'cfssl'
brew 'dnsmasq'
brew 'imagemagick'
brew 'jq'
brew 'openssl'
brew 'ttyrec'
brew 'unrar'
brew 'wget'
brew 'xz'

cask 'cleanmymac'
cask 'keybase'
cask 'wireshark'

mas  'Monosnap', id: 540348655
