################################################################################
### cloud ######################################################################
################################################################################
cask 'box-sync'
cask 'dropbox'
cask 'google-drive'
mas  'OneDrive', id: 823766827

brew 'awscli'
brew 'azure-cli'
cask 'bluemix-cli'
brew 'cf-cli'
brew 'heroku-toolbelt'
brew 'kubernetes-cli'
brew 'mesos'
cask 'minikube'
brew 'minimesos'

brew 'consul'
