################################################################################
### misc #######################################################################
################################################################################
cask 'adobe-acrobat-reader'
cask 'ableton-live-suite'
cask 'blender'
cask 'kindle'
cask 'monodraw'
cask 'musescore'
cask 'sketchup'
cask 'spectacle'
