################################################################################
### misc #######################################################################
################################################################################
cask 'adobe-acrobat-reader'
cask 'ableton-live-suite'
cask 'blender'
mas "GarageBand", id: 682658836
cask 'kindle'
cask 'monodraw'
cask 'musescore'
cask 'sketch'
cask 'spectacle'
