################################################################################
### initialize #################################################################
################################################################################

tap 'caskroom/cask'
tap 'caskroom/fonts'
tap 'caskroom/versions'

tap 'homebrew/cask-drivers'

tap 'ethereum/ethereum'
tap 'paritytech/paritytech'

brew 'mas'
