################################################################################
### stores #####################################################################
################################################################################
brew 'cassandra'
brew 'mariadb'
brew 'mongodb'
brew 'neo4j'
brew 'postgresql'
brew 'redis'
brew 'sqlite'

brew 'elasticsearch'

cask 'mysqlworkbench'
cask 'postico'

cask 'mongodbpreferencepane'
